### ISSUE TITLE
Improve Hash-Breaker Documentation

### ISSUE THREAD

**Issue by RobinHirst11** [KafetzisThomas/Hash-Breaker#2]
This issue proposes a significant enhancement to the Hash-Breaker documentation by adding a comprehensive section dedicated to practical usage examples, presented in a clear and concise terminal-like format. 

**Current Issues:**

* **Lack of Concrete Examples:** The current documentation primarily focuses on theoretical explanations of features and command-line arguments. It lacks the practical guidance provided by concrete usage examples.
* **Difficulty for Beginners:**  New users often struggle to grasp the tool's functionality and how to use it effectively due to the lack of practical demonstrations.
* **Inconsistent Documentation Style:** The current documentation lacks a consistent style, making it difficult for users to quickly find and understand the information they need.

**Proposed Changes:**

Inspired by the comprehensive and user-friendly approach used by The Fuck, we propose a dedicated "Usage Examples" section within the `README.md` file, using a terminal-like format to illustrate the tool's capabilities:

**Example 1: Cracking a hash with a wordlist:**

```bash
➜  hash_to_crack=e10adc3949ba59abbe56e057f20f883e  # Example MD5 hash
➜  wordlist_file=common_passwords.txt          # Path to wordlist file

# Using Hash-Breaker with a wordlist
➜  python main.py MD5 "$hash_to_crack" "$wordlist_file" --with-wordlist

# Output:
# ...
# Password found!
# Cracked password: password
```

**Example 2: Cracking a hash with dynamic password generation:**

```bash
➜  hash_to_crack=5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8  # Example SHA256 hash

# Using Hash-Breaker with dynamic password generation
➜  python main.py SHA256 "$hash_to_crack"

# Output:
# ...
# Generating passwords... 
# ...
# Password found!
# Cracked password: secret123
```

**Example 3: Using different hash algorithms:**

```bash
➜  bcrypt_hash=  # Replace with an example Bcrypt hash
➜  sha1_hash=   # Replace with an example SHA1 hash
➜  md5_hash=    # Replace with an example MD5 hash

# Cracking a Bcrypt hash
➜  python main.py Bcrypt "$bcrypt_hash" "$wordlist_file" --with-wordlist 

# Cracking a SHA1 hash
➜  python main.py SHA1 "$sha1_hash" 

# Cracking an MD5 hash 
➜  python main.py MD5 "$md5_hash" "$wordlist_file" --with-wordlist 
```

**Example 4: Customizing the character set for dynamic generation:**

```bash
➜  hash_to_crack=  # Replace with an example hash

# Using a custom character set for dynamic generation
➜  python main.py SHA256 "$hash_to_crack" --charset "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

# Output:
# ...
# Generating passwords using custom character set...
# ...
# Password found!
# Cracked password: MySecretPass
```

**Example 5: Handling errors and understanding the output:**

```bash
# Incorrect hash algorithm
➜  python main.py MD4 "$hash_to_crack"

# Output:
# Error: Unsupported hash algorithm: MD4

# Invalid wordlist path
➜  python main.py MD5 "$hash_to_crack" "invalid_wordlist.txt" --with-wordlist

# Output:
# Error: Wordlist file not found: invalid_wordlist.txt
```

**Benefits:**

* **Improved User Experience:**  The addition of comprehensive usage examples will significantly enhance the user experience by providing practical guidance and demonstrating the tool's capabilities.
* **Increased Clarity:**  Clear and concise examples will help users understand how to use the tool's features effectively and solve specific cracking problems.
* **Enhanced Learning:** Beginners will benefit from the practical examples as they gain a better understanding of hash cracking concepts through hands-on learning.
* **Improved Documentation Consistency:** A consistent terminal-like style will make the documentation easier to read and understand.

**This issue aims to elevate Hash-Breaker's documentation to a new level of clarity, organization, and user-friendliness, ultimately making the tool more valuable to its users.**

**Comment by KafetzisThomas** [comment]
Thank you for your insightful suggestions! I greatly appreciate your feedback and took it to heart to enhance the Hash-Breaker documentation significantly. Here's what I've implemented based on your ideas:

* Added a **dedicated usage examples** section for command-line args to provide comprehensive practical examples.
* **Enhanced the documentation style** for better clarity and consistency.

You can view the specific changes and additions in this commit: https://github.com/KafetzisThomas/Hash-Breaker/commit/ba37a28d53c3eb558aee451a53b330836c83c2b5

**Comment by RobinHirst11** [comment]
Awesome, looks great now, I might actually use this for a lot of my hashes. Now, what you need to implement is hash creation lmao, then this would be a seriously good tool.

**Comment by KafetzisThomas** [comment]
I'm glad you liked it! Regarding **hash creation**, I have made a simple script that operates via command-line arguments called `Message-Hasher` that you might find interesting: https://github.com/KafetzisThomas/Message-Hasher
